[package]
name = "texcore"
version = "0.2.3"
edition = "2021"
authors = ["Mustafif Khan"]
description = "Write latex in rust, and either compile it to pdf or output the tex code"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
tectonic = "0.9.0"
serde = { version = "1", features = ["derive"] }